ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "nb_helpers"
  site-url: "https://wandb.github.io/nb_helpers/"
  description: "A set of tools for nb handling"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/wandb/nb_helpers/tree/main/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/wandb/nb_helpers/tree/main/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
