name: Download

# read-write repo token
# access to secrets
on: 
  workflow_run:
    workflows: ["Upload"]
    types:
      - completed
defaults:
  run: { shell: bash }
jobs:
  download_payload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Run script
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      run: |
        pip install -Uq ghapi
        pip install -e .
        python .github/scripts/download.py