name: Reply PR
on: workflow_run:
  workflows: [Open in Colab]
defaults:
  run: { shell: bash }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Run script
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      run: |
        pip install -Uq ghapi
        pip install -e .
        python .github/scripts/reply_pr.py